services:
  - type: web
    name: cleanup-tracker
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health